site_name: Jaeger Documentation
# Don't show edit links
# edit_uri: edit/master/docs/
theme_dir: docs/theme
markdown_extensions:
  - admonition
  - codehilite
site_favicon: 'images/favicon.ico'
repo_name: 'jaegertracing/jaeger'
repo_url: 'https://github.com/jaegertracing/jaeger'
extra:
  logo: 'images/jaeger-logo.png'
google_analytics:
  - 'UA-97254222-1'
  - 'auto'
pages: 
  - 'Introduction': 'index.md'
  - 'Getting Started' : 'getting_started.md'
  - 'Features' : 'features.md'
  - 'Client Libraries' : 'client_libraries.md'
  - 'Architecture' : 'architecture.md'
  - 'Deployment' : 'deployment.md'
  - 'Monitoring' : 'monitoring.md'
  - 'Roadmap' : 'roadmap.md'
  - 'News' : 'news.md'
